export const ACTION_TYPES = {
  ADD: "ADD",
  REMOVE: "REMOVE",
  DELETE: "DELETE",
  CLEAR: "CLEAR_CART",
  COMPLETED: "COMPLETED_STEP",
  CLEAR_FORM_DATA: "CLEAR_FORM_DATA",
  SAVE_FORM_DATA: "SAVE_FORM_DATA"

};